version: '3'

services:

  web_server:
    image: nginx:alpine
    depends_on:
      - webapp
      - internal_vkapi
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
        
  webapp:
    build:
      context: ./webapp_service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    environment:
      MONGO_HOST: mongo
      AMQP_URI: rabbitmq
      AMQP_PORT: 5672
    env_file:
      - .env
    volumes:
      - ./webapp_service:/webapp_service
    ports:
      - 8000:8000
    command: uvicorn app:app --host 0.0.0.0
    
  internal_vkapi:
    build:
      context: ./internal_vk_api_service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    environment:
      AMQP_URI: rabbitmq
      AMQP_PORT: 5672
    env_file:
      - .env 
    volumes:
      - .:/internal_vk_api_service
    ports:
      - 5051:5051
    command: uvicorn app:app --host 0.0.0.0 --port 5051

volumes:
  data:
